language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 10
  - 11
  - 12
  - 13
  - 14
script:
  - npm run test
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
